### PR TITLE
Create workaround for trainingData not being passed on and write test…

### PR DESCRIPTION
**Pull request by btoomey**
…s for weighted linear reg with CV and CV with regularization. Note that CV with regularization still isn't finished, so that test is currently erroring.

### CODE REVIEW

**Comment by ramnathv** [comment]
@btoomey I am waiting to hear from you before (1) merging this to the master and (2) pushing it to svn.

**Comment by btoomey** [comment]
@ramnathv : I'm ready for this to be merged to master and pushed to SVN, assuming you're ok with that.

**Comment by ramnathv** [comment]
Did you run all the tests clean slate and update the test file? As long as the tests pass this is good to be merged to master and pushed to svn. I saw your notes on the refactoring, and they can be dealt with later by your team.

**Comment by btoomey** [comment]
@ramnathv : I ran the tests, but not after clearing my workspace, restarting R, etc. I'm going through that process now and will let you know once the tests finish.

**Comment by ramnathv** [comment]
Awesome. This will just ensure that we wont have any known test failures when Cindy downloads the build tomorrow morning.

**Comment by btoomey** [comment]
Weightedlinearwithcv failed when invoked via runTests2. But it passed when I ran it as an Alteryx workflow. I just tried runTests2 again; we'll see what happens.

**Comment by btoomey** [comment]
Oh, I think I know why the workflow passed and the R script didn't! The test uses randomly generated weights drawn from a normal distribution with mean 3 and sd 1, I think. So there's a slight chance in some cases that there could be a negative weight, and I think there was that one time. In any case, the tests all passed. But now I'll re-write it to ensure that the weights are never negative.

**Comment by ramnathv** [comment]
Great. Randomized tests are a double edged sword!

**Pull request merged**
